import feedparser
import os
import sys
from datetime import datetime, timezone, timedelta
import xml.etree.ElementTree as ET
from xml.dom import minidom
import json

# -----------------------------
# CONFIGURATION
# -----------------------------
FEEDS = [
"https://www.scientificamerican.com/platform/syndication/rss/",
"https://feeds.feedburner.com/zmescience",
    "https://phys.org/rss-feed/earth-news/",
    "https://feeds.newscientist.com/science-news",
    "https://www.thethirdpole.net/en/feed/",
    "https://www.carbonbrief.org/rss",
    "https://news.mongabay.com/news.xml",
    "https://politepaul.com/fd/kELFFnMAfctc.xml",
    "https://politepaul.com/fd/LmBK70i6qv46.xml",
    "https://theconversation.com/global/topics/climate-change-27/articles.atom"
]

MASTER_FILE = "feed_master.xml"
DAILY_FILE = "daily_feed.xml"
LAST_SEEN_FILE = "last_seen.json"

MAX_ITEMS = 500
BD_OFFSET = 6  # Bangladesh UTC offset

# Register namespace once at module level
ET.register_namespace('media', 'http://search.yahoo.com/mrss/')

# -----------------------------
# UTILITIES
# -----------------------------
def parse_date(entry):
    """Try multiple date fields from feedparser entry"""
    date_fields = ["published_parsed", "updated_parsed", "created_parsed"]
    for field in date_fields:
        t = getattr(entry, field, None)
        if t:
            return datetime(*t[:6], tzinfo=timezone.utc)
    return datetime.now(timezone.utc)

def extract_image(entry):
    """Extract image URL from feed entry"""
    # Try media:content
    if hasattr(entry, 'media_content') and entry.media_content:
        for media in entry.media_content:
            if 'url' in media:
                return media['url']

    # Try media:thumbnail
    if hasattr(entry, 'media_thumbnail') and entry.media_thumbnail:
        for thumb in entry.media_thumbnail:
            if 'url' in thumb:
                return thumb['url']

    # Try enclosure
    if hasattr(entry, 'enclosures') and entry.enclosures:
        for enc in entry.enclosures:
            if enc.get('type', '').startswith('image/'):
                return enc.get('url', '')

    # Try links with rel="enclosure"
    if hasattr(entry, 'links'):
        for link in entry.links:
            if link.get('rel') == 'enclosure' and link.get('type', '').startswith('image/'):
                return link.get('href', '')

    # Try parsing HTML content for first image
    content = getattr(entry, 'summary', '') or getattr(entry, 'content', [{}])[0].get('value', '')
    if content:
        import re
        img_match = re.search(r'<img[^>]+src=["\']([^"\']+)["\']', content, re.IGNORECASE)
        if img_match:
            return img_match.group(1)

    return None

def load_existing(file_path):
    """Load existing XML items"""
    if not os.path.exists(file_path):
        return []
    tree = ET.parse(file_path)
    root = tree.getroot()
    items = []
    for item in root.findall(".//item"):
        try:
            title = item.find("title").text or ""
            link = item.find("link").text or ""
            desc = item.find("description").text or ""
            pubDate = item.find("pubDate").text or ""
            pubDate_dt = datetime.strptime(pubDate, "%a, %d %b %Y %H:%M:%S %z")

            # Extract image
            image = None
            img_elem = item.find("{http://search.yahoo.com/mrss/}thumbnail")
            if img_elem is not None:
                image = img_elem.get("url")
            else:
                enc_elem = item.find("enclosure")
                if enc_elem is not None and enc_elem.get("type", "").startswith("image/"):
                    image = enc_elem.get("url")

            items.append({
                "title": title,
                "link": link,
                "description": desc,
                "pubDate": pubDate_dt,
                "image": image
            })
        except:
            continue
    return items

def write_rss(items, file_path, title="Feed"):
    """Write items to RSS XML with image support"""
    # Build XML string manually to avoid namespace issues
    xml_lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    xml_lines.append('<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">')
    xml_lines.append('  <channel>')
    xml_lines.append(f'    <title>{escape_xml(title)}</title>')
    xml_lines.append('    <link>https://evilgodfahim.github.io/</link>')
    xml_lines.append(f'    <description>{escape_xml(title + " generated by script")}</description>')
    
    for item in items:
        xml_lines.append('    <item>')
        xml_lines.append(f'      <title>{escape_xml(item["title"])}</title>')
        xml_lines.append(f'      <link>{escape_xml(item["link"])}</link>')
        xml_lines.append(f'      <description>{escape_xml(item["description"])}</description>')
        xml_lines.append(f'      <pubDate>{item["pubDate"].strftime("%a, %d %b %Y %H:%M:%S %z")}</pubDate>')
        
        # Add image if available
        if item.get("image"):
            xml_lines.append(f'      <media:thumbnail url="{escape_xml(item["image"])}" />')
            xml_lines.append(f'      <enclosure url="{escape_xml(item["image"])}" type="image/jpeg" />')
        
        xml_lines.append('    </item>')
    
    xml_lines.append('  </channel>')
    xml_lines.append('</rss>')
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write('\n'.join(xml_lines))

def escape_xml(text):
    """Escape special XML characters"""
    if not text:
        return ""
    text = str(text)
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    text = text.replace('"', "&quot;")
    text = text.replace("'", "&apos;")
    return text

# -----------------------------
# MASTER FEED UPDATE
# -----------------------------
def update_master():
    print("[Updating feed_master.xml]")
    existing = load_existing(MASTER_FILE)
    existing_links = {x["link"] for x in existing}
    new_items = []

    for url in FEEDS:
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                link = getattr(entry, "link", "")
                if link and link not in existing_links:
                    image = extract_image(entry)
                    new_items.append({
                        "title": getattr(entry, "title", "No Title"),
                        "link": link,
                        "description": getattr(entry, "summary", ""),
                        "pubDate": parse_date(entry),
                        "image": image
                    })
                    if image:
                        print(f"  📸 Found image: {image[:60]}...")
        except Exception as e:
            print(f"Error parsing {url}: {e}")

    all_items = existing + new_items
    all_items.sort(key=lambda x: x["pubDate"], reverse=True)
    all_items = all_items[:MAX_ITEMS]

    # Ensure at least one dummy item if empty
    if not all_items:
        all_items = [{
            "title": "No articles yet",
            "link": "https://evilgodfahim.github.io/",
            "description": "Master feed will populate after first successful fetch.",
            "pubDate": datetime.now(timezone.utc),
            "image": None
        }]

    write_rss(all_items, MASTER_FILE, title="Master Feed (Updated every 30 mins)")
    print(f"✅ feed_master.xml updated with {len(all_items)} items")
    print(f"   {sum(1 for i in all_items if i.get('image'))} items have images")

# -----------------------------
# DAILY FEED UPDATE
# -----------------------------
def update_daily():
    print("[Updating daily_feed.xml]")
    from_zone = timezone.utc
    to_zone = timezone(timedelta(hours=BD_OFFSET))

    # Load last seen
    if os.path.exists(LAST_SEEN_FILE):
        with open(LAST_SEEN_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
            last_seen = data.get("last_seen")
            if last_seen:
                last_seen_dt = datetime.fromisoformat(last_seen)
            else:
                last_seen_dt = None
    else:
        last_seen_dt = None

    master_items = load_existing(MASTER_FILE)
    new_items = []
    for item in master_items:
        pub = item["pubDate"].astimezone(to_zone)
        if not last_seen_dt or pub > last_seen_dt:
            new_items.append(item)

    if not new_items:
        new_items = [{
            "title": "No new articles today",
            "link": "https://evilgodfahim.github.io/",
            "description": "Daily feed will populate after first articles appear.",
            "pubDate": datetime.now(timezone.utc),
            "image": None
        }]

    write_rss(new_items, DAILY_FILE, title="Daily Feed (Updated 9 AM BD)")

    # Save last seen
    last_dt = max([i["pubDate"] for i in new_items])
    with open(LAST_SEEN_FILE, "w", encoding="utf-8") as f:
        json.dump({"last_seen": last_dt.isoformat()}, f)

    print(f"✅ daily_feed.xml updated with {len(new_items)} items")
    print(f"   {sum(1 for i in new_items if i.get('image'))} items have images")

# -----------------------------
# MAIN
# -----------------------------
if __name__ == "__main__":
    args = sys.argv[1:]
    if "--master-only" in args:
        update_master()
    elif "--daily-only" in args:
        update_daily()
    else:
        update_master()
        update_daily()